# Generated by Django 3.2 on 2022-08-03 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='filtering_user',
            field=models.ManyToManyField(blank=True, null=True, related_name='filtering_user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи'),
        ),
    ]
