# Generated by Django 3.2 on 2022-08-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0003_alter_mailing_filtering_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'verbose_name': 'Mailing', 'verbose_name_plural': 'Mailings'},
        ),
        migrations.AlterModelOptions(
            name='textmessage',
            options={'verbose_name': 'Text message', 'verbose_name_plural': 'Texts message'},
        ),
        migrations.AddField(
            model_name='textmessage',
            name='text_message',
            field=models.CharField(default='Hello, it`s text message', max_length=1000, verbose_name='Текст сообщения'),
        ),
        migrations.AlterField(
            model_name='textmessage',
            name='status',
            field=models.CharField(choices=[('Shipped', 'Отправлено'), ('Not_sent', 'Не отправлено')], default='Not_sent', max_length=120, verbose_name='Статус сообщения'),
        ),
    ]
