# Generated by Django 3.2 on 2022-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sender', '0004_auto_20220803_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='textmessage',
            name='text_message',
        ),
        migrations.AlterField(
            model_name='mailing',
            name='text_to_send',
            field=models.CharField(default='Hello, it`s text message', max_length=1000, verbose_name='Текст сообщения'),
        ),
    ]
