# Generated by Django 3.2 on 2022-08-03 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_code_mobile_operator'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Временая зона'),
        ),
    ]
