# Generated by Django 3.2 on 2022-08-03 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_time_zone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='time_zone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Временная зона'),
        ),
    ]
