# Generated by Django 3.2 on 2022-08-03 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender_user',
            field=models.CharField(choices=[('Man', 'Мужчина'), ('Women', 'Женщина'), ('Indefinite', 'Неопределенно')], default='Indefinite', max_length=120, verbose_name='Пол'),
        ),
    ]
